fix(express-engine, hapi-engine): remove `@nguniversal/module-map-ngfactory-loader` during `ng update`
String based lazy loading syntax is not support with Ivy and hence `@nguniversal/module-map-ngfactory-loader` is no longer required.

When not removed the application is left in a broken state with the following runtime error

```
NullInjectorError: R3InjectorError[router_RouterModule -> router_Router -> NgModuleFactoryLoader -> InjectionToken MODULE_MAP -> InjectionToken MODULE_MAP -> InjectionToken MODULE_MAP]:
```

Fixes: #1272