test: add `skipLibCheck` to hapi integration due to
```
ERROR in node_modules/@types/hapi__inert/node_modules/@types/hapi__hapi/index.d.ts:23:10 - error TS2305: Module '"@hapi/boom"' has no exported member 'Boom'.

```